blog/urls.py
from django.urls import path
from blog import views


app_name = 'mi_proyecto'  # Define el espacio de nombres

urlpatterns = [
    path('', views.blog_app, name='blog_app'),
    path('<int:id>/', views.detalle_de_entrada, name='detalle_de_entrada'),
    path('volver_app_inicio/', views.volver_app_inicio, name='volver_app_inicio'),
    path('post/<int:post_id>/', views.detalle_post, name='detalle_post'),


    # Agrega más rutas URL según las necesidades de tu blog
]

mi_proyecto/urls.py
from django.contrib import admin
from django.urls import path ,include
from mi_proyecto import views
from blog.views import blog_app
from django.conf import settings
from django.conf.urls.static import static


#app_name = 'mi_proyecto'
#from .views import *

urlpatterns = [
    path('', views.inicio, name='inicio'),  # Vista para la ruta principal '/'
    path('acerca_de/',views.acerca_de,name='acerca_de'),
    path('contacto/',views.contacto,name="contacto"),
    path('login/', views.login, name='login'),
    path('notas/', views.notas, name='notas'),
    path('admin/',admin.site.urls),
    path('generar_pdf/', views.generar_pdf, name='generar_pdf'),
    path('blog/', include('blog.urls', namespace='blog'),),
    path('blog/', blog_app,name='blog_app'),


    #path('redirigir_a_blog/', views.redirigir_a_blog, name='redirigir_a_blog'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

from django.db import models

class Post(models.Model):
    lista_areasConocimiento = (
        ('Educacion', 'Educación, Humanidades y Artes'),
        ('Ciencia_Sociales', 'Ciencias Sociales, Económicas, Administrativas y Derecho'),
        ('Ciencias_de_la_vida', 'Ciencias de la Vida'),
        ('Fisica', 'Física'),
        ('Matematicas_Y_Estadisticas', 'Matemáticas y Estadísticas'),
        ('Ingenieria', 'Ingeniería, Industria, Arquitectura e Informática'),
        ('Ciencias_Agropecuarias_Ambientales', 'Ciencias Agropecuarias y Ambientales'),
        ('Salud_Servicios_sociales_Bienestar', 'Salud, Servicios Sociales y Bienestar'),
    )

    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to='blog_images/', blank=True, null=True)
    pdf_file = models.FileField(upload_to='blog_pdfs/', blank=True, null=True)
    video = models.URLField(blank=True, null=True)
    fecha_de_publicacion = models.DateTimeField(auto_now_add=True)
    autor = models.CharField(max_length=100, null=False)
    categoria = models.CharField(max_length=255,choices=lista_areasConocimiento)

    def __str__(self):
        return self.title

blog/views.py
from django.urls import reverse
from django.shortcuts import redirect ,render ,get_object_or_404
from django.core.paginator import Paginator, Page

from django.urls import reverse
from .models import Post


def volver_app_inicio(request):
    # Construye la URL de la vista en app1 que deseas redirigir
    url_destino = reverse('inicio')

    # Realiza la redirección a la vista en app1
    return redirect(url_destino)

# Create your views here.

def blog_app(request):
    # Obtener todos los objetos Post ordenados por fecha de publicación en orden descendente
    posts = Post.objects.all().order_by('-fecha_de_publicacion')

    # Configurar la paginación
    paginator = Paginator(posts, 5)  # Divide las publicaciones en páginas de 10 elementos por página

    page_number = request.GET.get('page')  # Obtiene el número de página de la URL
    page = paginator.get_page(page_number)  # Obtiene la página actual

    # Definir el contexto con los posts paginados
    context = {
        'page': page,
    }

    # Renderizar la plantilla y pasar el contexto
    return render(request, 'blog.html', context)

def detalle_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    return render(request, 'detalle_post.html', {'post': post})



def detalle_de_entrada(request, id):
    # Lógica para recuperar la entrada del blog con el ID proporcionado
    entrada = Entrada.objects.get(pk=id)
    # Lógica adicional si es necesario
    return render(request, 'blog/detalle_de_entrada.html', {'entrada': entrada})

"""def posts(request):
    # Obtener todos los objetos Post
    posts = Post.objects.all()

    # Definir el contexto con los posts
    context = {
        'posts': posts,
    }

    # Renderizar la plantilla y pasar el contexto
    return render(request, 'postear.html', context)"""

blog/templates/base_blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css">
</head>
<body>
     <!-- para que se vea bien en dispositivos móviles -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <!-- Botón para activar el menú offcanvas -->
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasMenu" aria-controls="offcanvasMenu">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="{% url 'blog_app' %}">INVESTIGACION QUE TRANSFORMA</a>

                <!-- Menú offcanvas -->
                <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasMenu" aria-labelledby="offcanvasMenuLabel">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title" id="offcanvasMenuLabel">Tu puerta de entrada al repositorio nacional</h5>
                        <!-- Botón para cerrar el menú offcanvas -->
                        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'blog_app' %}">Inicio</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Iniciar secion</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Link</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link disabled" aria-current="page" href="{% url 'mi_proyecto:volver_app_inicio' %}"  >Mis notas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                            </li>
                        </ul>

                    </div>
                </div>
            </div>
         </nav>

    </header>

     {% block content %}
     {% endblock %}

     <!-- Footer -->
    <footer class="text-center" id="page-footer">
        <div class="container">
            <p class="font-weight-bold">Contacto: aderjasmirzeasrocha@gmail.com - Teléfono: 89278365</p>
            <p class="font-weight-bold">Sígueme en las redes sociales</p>
            <div class="container mt-5">
                <div class="d-inline mx-2">
                    <a href="https://twitter.com/Over_Ader" target="_blank" class="btn btn-info btn-lg">
                        <i class="fab fa-twitter me-2"></i> Twitter
                    </a>
                </div>
                <div class="d-inline mx-2">
                    <a href="https://www.linkedin.com/in/tu_perfil" target="_blank" class="btn btn-primary btn-lg">
                        <i class="fab fa-linkedin me-2"></i> LinkedIn
                    </a>
                </div>
                <div class="d-inline mx-2">
                    <a href="https://github.com/tu_usuario" target="_blank" class="btn btn-secondary btn-lg">
                        <i class="fab fa-github me-2"></i> GitHub
                    </a>
                </div>
            </div>
            <p class="font-weight-bold">&copy; {{ year }} Mi Proyecto. Todos los derechos reservados a Ader Yasmir Zeas Rocha.</p>
        </div>
    </footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% extends 'base_blog.html' %}
    {% block content %}



    {% include 'postear.html' %}
    {% endblock %}

</body>
</html>

<!--<a href="{% url 'blog:posts' %}"> Postes</a>-->

blog/templates/detalle_de_entrada.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 <h1>Rutas</h1>
</body>
</html>

blog/templates/detalle_post.html
<!DOCTYPE html>
<html>
<head>
    <title>Detalle del Post</title>
</head>
<body>
    {% extends 'base_blog.html' %}
    {% block content %}
    <div class="container mt-5 d-flex justify-content-center align-items-center">
        <div class="text-center">
            <h1 class="display-4">{{ post.title }}</h1>
            {% if post.image %}
            <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid">
            {% endif %}
            {% if post.video %}
            <div class="embed-responsive embed-responsive-16by9 mb-4 mt-4">
                <iframe class="embed-responsive-item embed-responsive-lg" src="{{ post.video }}" title="YouTube video player" allowfullscreen></iframe>
            </div>
            {% endif %}
            <p>{{ post.content }}</p>

            {% if post.pdf_file %}
               <p>
                    <a href="{{ post.pdf_file.url }}" target="_blank" class="btn btn-danger">
                        <i class="fas fa-eye"></i> Ver PDF
                    </a>
                    <a href="{{ post.pdf_file.url }}" download class="btn btn-danger">
                        <i class="fas fa-download"></i> Descargar PDF
                    </a>
                </p>

            {% endif %}

            <p><strong>Autor: {{ post.autor }}</strong></p>
        </div>
    </div>
    {% endblock %}
</body>
</html>

blog/templates/postear.html
<!DOCTYPE html>
<html>
<head>
    <title>Lista de Posts</title>
    <!-- Agrega los enlaces a Bootstrap CSS y jQuery (si es necesario) -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        <h1 class="display-2 text-center">Lista de Repositorio</h1>
        {% load static %}
        <ul class="list-group">
            {% for post in page %}
            <li class="list-group-item">
                <div class="row">
                    <div class="col-md-4">
                        {% if post.image %}
                        <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid">
                        {% endif %}
                    </div>
                    <div class="col-md-8">
                        <h2 class="h5 card-title">{{ post.title }}</h2>
                        <p class="card-text">{{ post.content|slice:":100" }}...</p>
                        <a href="{% url 'mi_proyecto:detalle_post' post.id %}" class="btn btn-primary">Leer más</a>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
        <div class="pagination justify-content-center">
            <span class="step-links">
                {% if page.has_previous %}
                    <a href="?page=1">&laquo; primera</a>
                    <a href="?page={{ page.previous_page_number }}">anterior</a>
                {% endif %}
                <span class="current-page">{{ page.number }}</span>
                {% if page.has_next %}
                    <a href="?page={{ page.next_page_number }}">siguiente</a>
                    <a href="?page={{ page.paginator.num_pages }}">última &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>

    <!-- Agrega los enlaces a Bootstrap JS y jQuery (si es necesario) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>